exclude:
  - 'node_modules'
layouts_dir: 'node_modules/uptick-demo-site/src'
package_name: Mireco
package_github_url: https://github.com/bor3ham/mireco
package_npm_url: https://www.npmjs.com/package/mireco
