import { init } from 'uptick-demo-site'

import './inputs/async-select'
import './inputs/button'
import './inputs/button-styles'
import './inputs/calendar-month'
import './inputs/checkbox'
import './inputs/date-range'
import './inputs/date'
import './inputs/datetime-range'
import './inputs/datetime'
import './inputs/duration'
import './inputs/number'
import './inputs/month'
import './inputs/multi-select'
import './inputs/range'
import './inputs/select'
import './inputs/text'
import './inputs/textarea'
import './inputs/time'
import './stress-test'

init()
