import { init } from 'uptick-demo-site'

import './components/basic/button'
import './components/basic/button-styles'
import './components/basic/checkbox'
import './components/basic/date'
import './components/basic/duration'
import './components/basic/number'
import './components/basic/multi-select'
import './components/basic/range'
import './components/basic/select'
import './components/basic/text'
import './components/basic/textarea'
import './components/basic/time'
import './components/compound/datetime'
import './components/compound/datetime-range'
import './components/compound/async-select'
import './stress-test'

init()
